version: "3"

services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - workspace-node_modules:/workspace/node_modules
    command: sleep infinity

volumes:
  workspace-node_modules:
